### PR TITLE
Added a quick README file.

### PR DESCRIPTION
**Pull request by avaidyam**
Any suggestions on what changes to make to it? We might want to add a disclaimer.

### CODE REVIEW

**Comment by jalembke** [comment]
I believe Dr. Comer mentioned wanting a disclaimer that this software is provided "as is" or something similar.  We probably also should direct visitors to the Xinu web site for more information.

**Comment by douglascomer** [comment]
Yes.  The declaration of "AS IS" is magic in the legal world because "AS IS" eliminates product liability.  Here's the notice we used in the past.

```
The sources are freely redistributable, provided they include the following notice, for example in a file named "COPYRIGHT" in the directory with the sources you distribute.

<<<begin COPYRIGHT>>>
Portions of this software are covered by the following copyright:

Copyright (c) 2012, 2015 by Douglas Comer and CRC Press, Inc. All rights reserved.

Redistribution and use in source and binary forms are permitted provided that this notice is preserved and that due credit is given to the copyright holders. The names of the copyright holders may not be used to endorse or promote products derived from this software without specific prior written permission. This software is provided "AS IS'' without express or implied warranty. The author assumes no liability for damages incidental or consequential, nor is the software warranted for correctness or suitability for any purpose.

Portions of this software are documented in the book:

Comer, D. E. [2015], "Operating System Desing - The Xinu Approach," Second edition, CRC PRess,  Boca Raton, Florida.

This software may not be sold or published in printed form without written permission from the copyright holders.
<<<<end COPYRIGHT>>>
```

**Comment by avaidyam** [comment]
@douglascomer Would that not be a `LICENSE` file instead then?

**Comment by douglascomer** [comment]
> @douglascomer Would that not be a `LICENSE` file instead then?

I haven't kept up with Intellectual Property law, and I don't know
the technical distinctions.  Twenty years ago, a lawyer recommended
COPYRIGHT.  Maybe we should label it COPYRIGHT-AND-LICENSE.

Prof. Comer

**Comment by avaidyam** [comment]
@douglascomer I've added a `COPYRIGHT.md` file.

What kind of information do we want in the `README.md` file? Previously it was the entirety of the Xinu webpage.

**Pull request closed without merging**
